Email Sender/Models/ErrorViewModel.cs
namespace Email_Sender.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Email Sender/Models/MailReqVm.cs
namespace Email_Sender.Models
{
    public class MailReqVm
    {
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}

Email Sender/Models/MailSettings.cs
namespace Email_Sender.Models
{
    public class MailSettings
    {
        public string Mail { get; set; }
        public string DisplayName { get; set; }
        public string Password { get; set; }
        public string Host { get; set; }
        public int Port { get; set; }
    }
}

Email Sender/Models/SendMailVm.cs
namespace Email_Sender.Models
{
    public class SendMailVm
    {
        public int Id { get; set; }
        public string ToEmail { get; set; }
    }
}

Email Sender/Controllers/EmailsRequestController.cs
using Email_Sender.Data;
using Email_Sender.Models;
using Email_Sender.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using MimeKit;

namespace Email_Sender.Controllers
{
    public class EmailsRequestController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IMailservice _mailservice;

        public EmailsRequestController(AppDbContext context, IMailservice mailservice)
        {
            this._db = context;
            this._mailservice = mailservice;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            //var MailsEeq = await _db.MailRequests.ToListAsync();
            var display = new CreateVM
            {
                dis = await _db.MailRequests.ToListAsync(),

            };


            return View(display);
        }
        [HttpPost]
        public async Task<IActionResult> Add(MailRequest mailRequest)

        {
            if (ModelState.IsValid)
            {
                await _db.AddAsync(new MailRequest
                {
                    Subject = mailRequest.Subject,
                    Message = mailRequest.Message,

                });
                await _db.SaveChangesAsync();
            }


            return RedirectToAction("Create");
        }

        public async Task<IActionResult> Send(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public async Task<IActionResult> SendTo(SendMailVm model)
        {

            var mailfromDb = await _db.MailRequests.FindAsync(model.Id);
            MailReqVm mailReqVm = new MailReqVm
            {
                Subject = mailfromDb.Subject,
                Message = mailfromDb.Message,
            };

            if (mailfromDb == null)
            {
                return BadRequest(ModelState);
            }

            List<string> emailadress = new List<string>();
            var mailto = model.ToEmail.Split(',');
            foreach (var mail in mailto)
            {
                emailadress.Add(mail);
            }
         
                await _mailservice.SendEmailAsync(emailadress, mailReqVm.Subject, mailReqVm.Message);

            
        


            return Ok();
        }
    }
}

Email Sender/Controllers/HomeController.cs
using Email_Sender.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Email_Sender.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Email Sender/Views/EmailsRequest/Create.cshtml
@*@model IEnumerable<Email_Sender.Data.MailRequest>
*@ 
@model Email_Sender.Data.CreateVM

<div class="mb-3">
    <div asp-validation-summary="ModelOnly"></div>
    <form asp-action="Add" method="post">

        <div class="mb-3 col-md-4">

            <label  class="form-label col-md-4 ">Subject</label>
            <input  asp-for="input.Subject" name="Subject" type="text" class="form-control Subject form-control-lg col-md-4">
            <span asp-validation-for="input.Subject" class="text-danger field-validation-error"></span>


        </div>
        <div class="mb-3 col-md-4">
            <label class="form-label">Message</label>
            <input  asp-for="input.Message" name="Message" type="text" class="form-control Message form-control-lg">
            <span asp-validation-for="input.Message" class="text-danger field-validation-error"></span>

        </div>
        <button type="submit" class="btn btn-primary add">Add</button>
    </form>
</div>
<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
        <tr>
            <th>Subject</th>
            <th>Send</th>

        </tr>
    </thead>
    <tbody id="body">
        @foreach (var item in Model.dis)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model=>item.Subject)

                </td>

                <td>
                    <a class="Send"
                   title="Send"
                   role="button"
                   data-id="@item.Id"
                   asp-action="Send"
                   asp-route-id="@item.Id">


                        Send
                    </a>
                </td>

            </tr>


        }



    </tbody>
</table>
@section Scripts
{
  <partial name="_ValidationScriptsPartial"/>    

}
@*<script>

    $(document).ready(function()
    {

        //$('.add').on('click',function(){
        //    let obj={
        //        Subject:$('.Subject').val(),
        //        Message:$('.Message').val(),

        //    }
        //     $.ajax({
        //          url:'/EmailsRequest/Add/',
        //          method:'POST',
        //          data:obj,
        //          success:function(res){


        //               },
        //           error:function(res){

        //           },


        //     });
        //});


    });
</script>
*@

Email Sender/Views/EmailsRequest/Send.cshtml
@model Email_Sender.Models.SendMailVm

<form asp-action="SendTo">
  <input class="form-control form-control-lg"
    type="hidden" name="Id" id="Id" value="@ViewBag.Id" asp-for="Id"
    >
<div class="mb-3 row col-md-5" >
  <label asp-for="ToEmail" class="form-label">To</label>
    <input class="form-control form-control-lg"
    type="text" asp-for="ToEmail"
    >
</div>
<button type="submit" class="btn btn-primary">Send</button>

<a asp-action="Create" type="button" class="btn btn-secondary">Back</a>
</form>

Email Sender/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Email Sender/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Email_Sender</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
@*    <link rel="stylesheet" href="~/Email_Sender.styles.css" asp-append-version="true" />
*@</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Email_Sender</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                   @*     <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmailsRequest" asp-action="Create">Emails Request</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial"); 
    }
    }
</body>
</html>